Update requirements.txt for new tensorflow naming
The tensorflow package has removed the -gpu naming convention (i.e., tensorflow-gpu).  See error below

× python setup.py bdist_wheel did not run successfully.                                                                                                                                                                                                                          
  │ exit code: 1                                                                                                                                                                                                                                                                   
  ╰─> [18 lines of output]                                                                                                                                                                                                                                                         
      Traceback (most recent call last):                                                                                                                                                                                                                                           
        File "<string>", line 2, in <module>                                                                                                                                                                                                                                       
        File "<pip-setuptools-caller>", line 34, in <module>                                                                                                                                                                                                                       
        File "/tmp/pip-install-felssefm/tensorflow-gpu_a5be125bd36342c4a582a89ba7235ad4/setup.py", line 37, in <module>                                                                                                                                                            
          raise Exception(TF_REMOVAL_WARNING)                                                                                                                                                                                                                                      
      Exception:                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                   
      =========================================================                                                                                                                                                                                                                    
      The "tensorflow-gpu" package has been removed!                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                   
      Please install "tensorflow" instead.                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                   
      Other than the name, the two packages have been identical                                                                                                                                                                                                                    
      since TensorFlow 2.1, or roughly since Sep 2019. For more                                                                                                                                                                                                                    
      information, see: pypi.org/project/tensorflow-gpu                                                                                                                                                                                                                            
      =========================================================  

The change here installs tensorflow with GPU support as can be seen from the build output:

Requirement already satisfied: pandas>=1.2.2 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 1)) (1.5.0)
Requirement already satisfied: tensorflow[and-cuda]>=2.12 in /home/htony/.local/lib/python3.10/site-packages (from -r requirements.txt (line 2)) (2.16.1)
Requirement already satisfied: numpy>=1.19.5 in /home/htony/.local/lib/python3.10/site-packages (from -r requirements.txt (line 3)) (1.26.4)
Requirement already satisfied: h5py>=3.1.0 in /home/htony/.local/lib/python3.10/site-packages (from -r requirements.txt (line 4)) (3.11.0)
Requirement already satisfied: scipy>=1.6.0 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 5)) (1.8.0)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/lib/python3/dist-packages (from pandas>=1.2.2->-r requirements.txt (line 1)) (2.8.1)
Requirement already satisfied: pytz>=2020.1 in /usr/lib/python3/dist-packages (from pandas>=1.2.2->-r requirements.txt (line 1)) (2022.1)
Requirement already satisfied: six>=1.12.0 in /usr/lib/python3/dist-packages (from tensorflow[and-cuda]>=2.12->-r requirements.txt (line 2)) (1.16.0)
Requirement already satisfied: tensorboard<2.17,>=2.16 in /home/htony/.local/lib/python3.10/site-packages (from tensorflow[and-cuda]>=2.12->-r requirements.txt (line 2)) (2.16.2)
Requirement already satisfied: setuptools in /usr/lib/python3/dist-packages (from tensorflow[and-cuda]>=2.12->-r requirements.txt (line 2)) (59.6.0)
Requirement already satisfied: absl-py>=1.0.0 in /home/htony/.local/lib/python3.10/site-packages (from tensorflow[and-cuda]>=2.12->-r requirements.txt (line 2)) (2.1.0)
Requirement already satisfied: wrapt>=1.11.0 in /home/htony/.local/lib/python3.10/site-packages (from tensorflow[and-cuda]>=2.12->-r requirements.txt (line 2)) (1.16.0)
Requirement already satisfied: astunparse>=1.6.0 in /home/htony/.local/lib/python3.10/site-packages (from tensorflow[and-cuda]>=2.12->-r requirements.txt (line 2)) (1.6.3)
Requirement already satisfied: ml-dtypes~=0.3.1 in /home/htony/.local/lib/python3.10/site-packages (from tensorflow[and-cuda]>=2.12->-r requirements.txt (line 2)) (0.3.2)
Requirement already satisfied: flatbuffers>=23.5.26 in /home/htony/.local/lib/python3.10/site-packages (from tensorflow[and-cuda]>=2.12->-r requirements.txt (line 2)) (24.3.25)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.20.3 in /home/htony/.local/lib/python3.10/site-packages (from tensorflow[and-cuda]>=2.12->-r requirements.txt (line 2)) (4.25.3)
Requirement already satisfied: opt-einsum>=2.3.2 in /home/htony/.local/lib/python3.10/site-packages (from tensorflow[and-cuda]>=2.12->-r requirements.txt (line 2)) (3.3.0)
Requirement already satisfied: requests<3,>=2.21.0 in /usr/lib/python3/dist-packages (from tensorflow[and-cuda]>=2.12->-r requirements.txt (line 2)) (2.25.1)
Requirement already satisfied: libclang>=13.0.0 in /home/htony/.local/lib/python3.10/site-packages (from tensorflow[and-cuda]>=2.12->-r requirements.txt (line 2)) (18.1.1)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /home/htony/.local/lib/python3.10/site-packages (from tensorflow[and-cuda]>=2.12->-r requirements.txt (line 2)) (1.63.0)
Requirement already satisfied: keras>=3.0.0 in /home/htony/.local/lib/python3.10/site-packages (from tensorflow[and-cuda]>=2.12->-r requirements.txt (line 2)) (3.3.3)
Requirement already satisfied: termcolor>=1.1.0 in /home/htony/.local/lib/python3.10/site-packages (from tensorflow[and-cuda]>=2.12->-r requirements.txt (line 2)) (2.4.0)
Requirement already satisfied: packaging in /usr/lib/python3/dist-packages (from tensorflow[and-cuda]>=2.12->-r requirements.txt (line 2)) (21.3)
Requirement already satisfied: google-pasta>=0.1.1 in /home/htony/.local/lib/python3.10/site-packages (from tensorflow[and-cuda]>=2.12->-r requirements.txt (line 2)) (0.2.0)
Requirement already satisfied: typing-extensions>=3.6.6 in /home/htony/.local/lib/python3.10/site-packages (from tensorflow[and-cuda]>=2.12->-r requirements.txt (line 2)) (4.11.0)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /home/htony/.local/lib/python3.10/site-packages (from tensorflow[and-cuda]>=2.12->-r requirements.txt (line 2)) (0.5.4)
Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.23.1 in /home/htony/.local/lib/python3.10/site-packages (from tensorflow[and-cuda]>=2.12->-r requirements.txt (line 2)) (0.37.0)
Requirement already satisfied: nvidia-cuda-nvcc-cu12==12.3.107 in /home/htony/.local/lib/python3.10/site-packages (from tensorflow[and-cuda]>=2.12->-r requirements.txt (line 2)) (12.3.107)
Requirement already satisfied: nvidia-curand-cu12==10.3.4.107 in /home/htony/.local/lib/python3.10/site-packages (from tensorflow[and-cuda]>=2.12->-r requirements.txt (line 2)) (10.3.4.107)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.3.101 in /home/htony/.local/lib/python3.10/site-packages (from tensorflow[and-cuda]>=2.12->-r requirements.txt (line 2)) (12.3.101)
Requirement already satisfied: nvidia-cusparse-cu12==12.2.0.103 in /home/htony/.local/lib/python3.10/site-packages (from tensorflow[and-cuda]>=2.12->-r requirements.txt (line 2)) (12.2.0.103)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.3.101 in /home/htony/.local/lib/python3.10/site-packages (from tensorflow[and-cuda]>=2.12->-r requirements.txt (line 2)) (12.3.101)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.3.107 in /home/htony/.local/lib/python3.10/site-packages (from tensorflow[and-cuda]>=2.12->-r requirements.txt (line 2)) (12.3.107)
Requirement already satisfied: nvidia-cublas-cu12==12.3.4.1 in /home/htony/.local/lib/python3.10/site-packages (from tensorflow[and-cuda]>=2.12->-r requirements.txt (line 2)) (12.3.4.1)
Requirement already satisfied: nvidia-nccl-cu12==2.19.3 in /home/htony/.local/lib/python3.10/site-packages (from tensorflow[and-cuda]>=2.12->-r requirements.txt (line 2)) (2.19.3)
Requirement already satisfied: nvidia-cufft-cu12==11.0.12.1 in /home/htony/.local/lib/python3.10/site-packages (from tensorflow[and-cuda]>=2.12->-r requirements.txt (line 2)) (11.0.12.1)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.3.101 in /home/htony/.local/lib/python3.10/site-packages (from tensorflow[and-cuda]>=2.12->-r requirements.txt (line 2)) (12.3.101)
Requirement already satisfied: nvidia-cusolver-cu12==11.5.4.101 in /home/htony/.local/lib/python3.10/site-packages (from tensorflow[and-cuda]>=2.12->-r requirements.txt (line 2)) (11.5.4.101)
Requirement already satisfied: nvidia-cudnn-cu12==8.9.7.29 in /home/htony/.local/lib/python3.10/site-packages (from tensorflow[and-cuda]>=2.12->-r requirements.txt (line 2)) (8.9.7.29)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/lib/python3/dist-packages (from astunparse>=1.6.0->tensorflow[and-cuda]>=2.12->-r requirements.txt (line 2)) (0.37.1)
Requirement already satisfied: namex in /home/htony/.local/lib/python3.10/site-packages (from keras>=3.0.0->tensorflow[and-cuda]>=2.12->-r requirements.txt (line 2)) (0.0.8)
Requirement already satisfied: rich in /home/htony/.local/lib/python3.10/site-packages (from keras>=3.0.0->tensorflow[and-cuda]>=2.12->-r requirements.txt (line 2)) (13.7.1)
Requirement already satisfied: optree in /home/htony/.local/lib/python3.10/site-packages (from keras>=3.0.0->tensorflow[and-cuda]>=2.12->-r requirements.txt (line 2)) (0.11.0)
Requirement already satisfied: markdown>=2.6.8 in /home/htony/.local/lib/python3.10/site-packages (from tensorboard<2.17,>=2.16->tensorflow[and-cuda]>=2.12->-r requirements.txt (line 2)) (3.6)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /home/htony/.local/lib/python3.10/site-packages (from tensorboard<2.17,>=2.16->tensorflow[and-cuda]>=2.12->-r requirements.txt (line 2)) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in /home/htony/.local/lib/python3.10/site-packages (from tensorboard<2.17,>=2.16->tensorflow[and-cuda]>=2.12->-r requirements.txt (line 2)) (3.0.2)
Requirement already satisfied: MarkupSafe>=2.1.1 in /home/htony/.local/lib/python3.10/site-packages (from werkzeug>=1.0.1->tensorboard<2.17,>=2.16->tensorflow[and-cuda]>=2.12->-r requirements.txt (line 2)) (2.1.5)
Requirement already satisfied: markdown-it-py>=2.2.0 in /home/htony/.local/lib/python3.10/site-packages (from rich->keras>=3.0.0->tensorflow[and-cuda]>=2.12->-r requirements.txt (line 2)) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /home/htony/.local/lib/python3.10/site-packages (from rich->keras>=3.0.0->tensorflow[and-cuda]>=2.12->-r requirements.txt (line 2)) (2.17.2)
Requirement already satisfied: mdurl~=0.1 in /home/htony/.local/lib/python3.10/site-packages (from markdown-it-py>=2.2.0->rich->keras>=3.0.0->tensorflow[and-cuda]>=2.12->-r requirements.txt (line 2)) (0.1.2)